name: CI/CD - Deploy a Google Cloud Run

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Autenticarse con Google Cloud
        uses: google-github-actions/auth@v1
        with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Subir imagen backend
        run: |
          gcloud builds submit ./backend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-notas

      - name: Desplegar backend
        run: |
          gcloud run deploy backend-notas \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-notas \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Subir imagen frontend
        run: |
          gcloud builds submit ./frontend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-notas

      - name: Desplegar frontend
        run: |
          gcloud run deploy frontend-notas \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-notas \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated